# Generated by Django 5.1.7 on 2025-03-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя водителя')),
                ('license_issue_date', models.DateField(verbose_name='Дата выдачи прав')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Вывод прибыли',
                'verbose_name_plural': 'Выводы прибыли',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField(verbose_name='Расстояние')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_routes', to='accounts.city', verbose_name='Город назначения')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='accounts.city', verbose_name='Город отправления')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_weight', models.FloatField(verbose_name='Вес груза')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='Клиент')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='TripDriver',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver', verbose_name='Водитель')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Водитель поездки',
                'verbose_name_plural': 'Водители поездок',
            },
        ),
        migrations.CreateModel(
            name='TripService',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.additionalservice', verbose_name='Услуга')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Услуга поездки',
                'verbose_name_plural': 'Услуги поездок',
            },
        ),
    ]
